
package act2_2_xsd;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
    Alumno: Ari Santiago Piceno Rodríguez
    Registro:23300223
    Grado y Grupo: 4C1
    
    Materia: POO 2 (Programación Orientada a Objetos 2)
    Carrera: Desarrollo de Software
    Producto: Act4 Practica de Validacion XSD
    Profe: ROA
    
    Fecha: 15/mayo/2025
    
    */

public class Cajero extends javax.swing.JFrame {
    
    private HashMap<Integer, Cajeros> diccio;
    private int numCJ;
    private Principal padre;
    private int val;
    public Cajero(Principal padre, HashMap<Integer, Cajeros> diccio, int numCJ) {
        initComponents();
        this.padre=padre;
        this.numCJ = numCJ;
        this.diccio = diccio;
        this.val = 0;
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension d=tk.getScreenSize();
        setSize(704, 520);
        setLocation((d.width-getSize().width)/2,(d.height-getSize().height)/2);
        setDefaultCloseOperation (DISPOSE_ON_CLOSE);
        setTitle("Banco Internacional de Hyrule (BIH)");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNumCajero = new javax.swing.JLabel();
        txtNumCajero = new javax.swing.JTextField();
        javax.swing.JLabel lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApp = new javax.swing.JLabel();
        txtApp = new javax.swing.JTextField();
        lblApm = new javax.swing.JLabel();
        txtApm = new javax.swing.JTextField();
        lblF_Inicial = new javax.swing.JLabel();
        txtF_Inicial = new javax.swing.JTextField();
        lblF_Final = new javax.swing.JLabel();
        txtF_Final = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CAJEROS");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(250, 20, 170, 50);

        lblNumCajero.setText("Numero Empleado:");
        getContentPane().add(lblNumCajero);
        lblNumCajero.setBounds(80, 100, 130, 16);
        getContentPane().add(txtNumCajero);
        txtNumCajero.setBounds(220, 90, 380, 30);

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(80, 140, 130, 16);

        txtNombre.setEnabled(false);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(220, 130, 380, 30);

        lblApp.setText("Apellido Paterno");
        getContentPane().add(lblApp);
        lblApp.setBounds(80, 180, 130, 16);

        txtApp.setEnabled(false);
        getContentPane().add(txtApp);
        txtApp.setBounds(220, 170, 380, 30);

        lblApm.setText("Apellido Materno:");
        getContentPane().add(lblApm);
        lblApm.setBounds(80, 220, 130, 16);

        txtApm.setEnabled(false);
        getContentPane().add(txtApm);
        txtApm.setBounds(220, 210, 380, 30);

        lblF_Inicial.setText("Fondo Inicial:");
        getContentPane().add(lblF_Inicial);
        lblF_Inicial.setBounds(80, 260, 130, 16);

        txtF_Inicial.setEnabled(false);
        getContentPane().add(txtF_Inicial);
        txtF_Inicial.setBounds(220, 250, 380, 30);

        lblF_Final.setText("Fondo Final:");
        getContentPane().add(lblF_Final);
        lblF_Final.setBounds(80, 300, 130, 16);

        txtF_Final.setEnabled(false);
        getContentPane().add(txtF_Final);
        txtF_Final.setBounds(220, 290, 380, 30);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(500, 360, 100, 60);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(110, 360, 100, 60);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(240, 360, 100, 60);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(370, 360, 100, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if (btnNuevo.getText().equals("Nuevo"))
        {
            txtNumCajero.setText(String.valueOf(numCJ+1));
            txtNombre.setEnabled(true);
            txtNumCajero.setEditable(false);
            txtApp.setEnabled(true);
            txtApm.setEnabled(true);
            txtF_Inicial.setEnabled(true);
            txtF_Final.setEnabled(true);
            btnNuevo.setText("Guardar");
            btnBuscar.setEnabled(false);
            btnSalir.setText("Cancelar");
            txtNumCajero.requestFocus();
        }
        else if (btnNuevo.getText().equals("Guardar"))
        {
            if (txtNumCajero.getText().equals("")||txtNombre.getText().equals("")||
                    txtApp.getText().equals("")||txtApm.getText().equals("")||txtF_Inicial.getText().equals("")||
                    txtF_Final.getText().equals(""))
            {
                JOptionPane.showMessageDialog(getMe(),"Completa todos los campos","Banco Intenacional de Hyrule(BIH)",JOptionPane.ERROR_MESSAGE);
                return;

            }
            Cajeros c=new Cajeros();
            c.setNumEmpleado(numCJ+1);
            c.setNombre(txtNombre.getText());
            c.setApp(txtApp.getText());
            c.setApm(txtApm.getText());
            try{
                c.setFondoInicial(Double.parseDouble(txtF_Inicial.getText()));
                c.setFondoFinal(Double.parseDouble(txtF_Final.getText()));
            
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(getMe(),"Error en el formato de Fondo Inicial y/o Final de Cajero","Banco Intenacional de Hyrule(BIH)",JOptionPane.ERROR_MESSAGE);
                return;
            }
            numCJ++;
            diccio.put(numCJ, c);
            resetear();
        }
         
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (btnBuscar.getText().equals("Buscar"))
        {
            if (!txtNumCajero.getText().equals(""))
            {
                try{
                    val = Integer.parseInt(txtNumCajero.getText());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(getMe(),"El Formato del Numero de Cajero No es el Adecuado","Banco Intenacional de Hyrule(BIH)", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Cajeros tmp = null;
                if (diccio.get(val) != null)
                {   
                    tmp = diccio.get(val);
                    txtNombre.setText(tmp.getNombre());
                    txtApp.setText(tmp.getApp());
                    txtApm.setText(tmp.getApm());
                    txtF_Inicial.setText(String.valueOf(tmp.getFondoInicial()));
                    txtF_Final.setText(String.valueOf(tmp.getFondoFinal()));
                    btnNuevo.setEnabled(false);
                    btnBuscar.setText("Modificar");
                    btnEliminar.setEnabled(true);
                    btnSalir.setText("Cancelar");
                }
                else 
                {
                    JOptionPane.showMessageDialog(getMe(), "El Cajero numero \"" + val + "\" NO EXISTE", "Banco Intenacional de Hyrule(BIH)", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        else if (btnBuscar.getText().equals("Modificar"))
        {
            txtNumCajero.setEnabled(false);
            txtNombre.setEnabled(true);
            txtApp.setEnabled(true);
            txtApm.setEnabled(true);
            txtF_Inicial.setEnabled(true);
            txtF_Final.setEnabled(true);
            btnBuscar.setText("Guardar");
            btnEliminar.setEnabled(false);
            txtNombre.requestFocus();
        }
        else if (btnBuscar.getText().equals("Guardar"))
        {
            Cajeros c;
            c=diccio.get(val);
            c.setNombre(txtNombre.getText());
            c.setApp(txtApp.getText());
            c.setApm(txtApm.getText());
            try{
                c.setFondoInicial(Double.parseDouble(txtF_Inicial.getText()));
                c.setFondoFinal(Double.parseDouble(txtF_Final.getText()));
            
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(getMe(),"Error en el formato de Fondo Inicial y/o Final de Cajero","Banco Intenacional de Hyrule(BIH)",JOptionPane.ERROR_MESSAGE);
                return;
            }
            resetear();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(getMe(), "¿Estas seguro de eliminarlo?", "Banco Internacional de Hyrule (BIH)", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            diccio.remove(val);
            resetear();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (btnSalir.getText().equals("Salir"))
        {
            padre.setNumCJ(numCJ);
            padre.setVisible(true);
            this.dispose();
        }
        else
        {
            resetear();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        padre.setNumCJ(numCJ);
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
private void resetear()
{
            txtNumCajero.setText("");
            btnEliminar.setEnabled(false);
            txtNumCajero.setEnabled(true);
            txtNumCajero.setEditable(true);
            txtNombre.setEnabled(false);
            txtNombre.setText("");
            txtApp.setEnabled(false);
            txtApp.setText("");
            txtApm.setEnabled(false);
            txtApm.setText("");
            txtF_Inicial.setEnabled(false);
            txtF_Inicial.setText("");
            txtF_Final.setEnabled(false);
            txtF_Final.setText("");
            btnNuevo.setText("Nuevo");
            btnBuscar.setEnabled(true);
            btnSalir.setText("Salir");
            btnNuevo.setEnabled(true);
            btnBuscar.setText("Buscar");
            txtNumCajero.requestFocus();
}
    public Cajero getMe()
    {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblApm;
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblF_Final;
    private javax.swing.JLabel lblF_Inicial;
    private javax.swing.JLabel lblNumCajero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApm;
    private javax.swing.JTextField txtApp;
    private javax.swing.JTextField txtF_Final;
    private javax.swing.JTextField txtF_Inicial;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCajero;
    // End of variables declaration//GEN-END:variables
}
