
package act2_2_xsd;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
    Alumno: Ari Santiago Piceno Rodríguez
    Registro:23300223
    Grado y Grupo: 4C1
    
    Materia: POO 2 (Programación Orientada a Objetos 2)
    Carrera: Desarrollo de Software
    Producto: Act4 Practica de Validacion XSD
    Profe: ROA
    
    Fecha: 15/mayo/2025
    
    */

public class Cliente extends javax.swing.JFrame {
    
    private HashMap<Integer, Clientes> diccio;
    private int numCL;
    private Principal padre;
    private int val;
    public Cliente(Principal padre,HashMap<Integer, Clientes> diccio, int numCL) {
        initComponents();
        this.padre=padre;
        this.numCL = numCL;
        this.diccio = diccio;
        this.val = 0;
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension d=tk.getScreenSize();
        setSize(704, 543);
        setLocation((d.width-getSize().width)/2,(d.height-getSize().height)/2);
        setDefaultCloseOperation (DISPOSE_ON_CLOSE);
        setTitle("Banco Internacional de Hyrule (BIH)");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNumCliente = new javax.swing.JLabel();
        txtNumCliente = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApp = new javax.swing.JLabel();
        txtApp = new javax.swing.JTextField();
        lblApm = new javax.swing.JLabel();
        txtApm = new javax.swing.JTextField();
        lblRFC = new javax.swing.JLabel();
        txtRFC = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblSalarioMensual = new javax.swing.JLabel();
        txtSalarioMensual = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("CLIENTES");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(250, 20, 170, 50);

        lblNumCliente.setText("Numero Cliente:");
        getContentPane().add(lblNumCliente);
        lblNumCliente.setBounds(80, 100, 130, 16);
        getContentPane().add(txtNumCliente);
        txtNumCliente.setBounds(220, 90, 380, 30);

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(80, 140, 130, 16);

        txtNombre.setEnabled(false);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(220, 130, 380, 30);

        lblApp.setText("Apellido Paterno");
        getContentPane().add(lblApp);
        lblApp.setBounds(80, 180, 130, 16);

        txtApp.setEnabled(false);
        getContentPane().add(txtApp);
        txtApp.setBounds(220, 170, 380, 30);

        lblApm.setText("Apellido Materno:");
        getContentPane().add(lblApm);
        lblApm.setBounds(80, 220, 130, 16);

        txtApm.setEnabled(false);
        getContentPane().add(txtApm);
        txtApm.setBounds(220, 210, 380, 30);

        lblRFC.setText("RFC:");
        getContentPane().add(lblRFC);
        lblRFC.setBounds(80, 260, 130, 16);

        txtRFC.setEnabled(false);
        getContentPane().add(txtRFC);
        txtRFC.setBounds(220, 250, 380, 30);

        lblTipo.setText("Tipo de Cliente:");
        getContentPane().add(lblTipo);
        lblTipo.setBounds(80, 300, 130, 16);

        lblSalarioMensual.setText("Salario Mensual:");
        getContentPane().add(lblSalarioMensual);
        lblSalarioMensual.setBounds(80, 340, 130, 16);

        txtSalarioMensual.setEnabled(false);
        getContentPane().add(txtSalarioMensual);
        txtSalarioMensual.setBounds(220, 330, 380, 30);

        lblDireccion.setText("Direccion:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(80, 380, 130, 16);

        txtDireccion.setEnabled(false);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(220, 370, 380, 30);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Preferente", "VIP" }));
        cmbTipo.setEnabled(false);
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(220, 292, 380, 30);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(500, 430, 100, 60);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(110, 430, 100, 60);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(240, 430, 100, 60);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(370, 430, 100, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if (btnNuevo.getText().equals("Nuevo"))
        {   
            txtNumCliente.setText(String.valueOf(numCL+1));
            txtNumCliente.setEditable(false);
            txtNombre.setEnabled(true);
            txtApp.setEnabled(true);
            txtApm.setEnabled(true);
            txtRFC.setEnabled(true);
            cmbTipo.setEnabled(true);
            txtSalarioMensual.setEnabled(true);
            txtDireccion.setEnabled(true);
            btnNuevo.setText("Guardar");
            btnBuscar.setEnabled(false);
            btnSalir.setText("Cancelar");
            txtNumCliente.requestFocus();
        }
        else if (btnNuevo.getText().equals("Guardar"))
        {
            if (txtNumCliente.getText().equals("")||txtNombre.getText().equals("")||
                    txtApp.getText().equals("")||txtApm.getText().equals("")||txtRFC.getText().equals("")||
                    txtSalarioMensual.getText().equals("")||txtDireccion.getText().equals(""))
            {
                JOptionPane.showMessageDialog(getMe(),"Completa todos los campos","Banco Intenacional de Hyrule(BIH)",JOptionPane.ERROR_MESSAGE);
                return;
            }
            Clientes c=new Clientes();
            c.setNumCliente(numCL+1);
            c.setNombre(txtNombre.getText());
            c.setApp(txtApp.getText());
            c.setApm(txtApm.getText());
            c.setRfc(txtRFC.getText());
            c.setTipo(((String)cmbTipo.getSelectedItem()).charAt(0));
            try{
                c.setSalarioMensual(Double.parseDouble(txtSalarioMensual.getText()));
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(getMe(),"Error en el formato del salario mensual del cliente","Banco Intenacional de Hyrule(BIH)",JOptionPane.ERROR_MESSAGE);
                return;
            }
            c.setDireccion(txtDireccion.getText());
            numCL++;
            diccio.put(numCL, c);
            resetear();
            
        }
         
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (btnBuscar.getText().equals("Buscar"))
        {
            if (!txtNumCliente.getText().equals(""))
            {
                Clientes tmp=null;
                try{
                    val = Integer.parseInt(txtNumCliente.getText());
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(getMe(), "El Formato del Numero de Cajero No es el Adecuado","Banco Intenacional de Hyrule(BIH)", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (diccio.get(val) != null)
                {
                    tmp = diccio.get(val);
                    txtNombre.setText(tmp.getNombre());
                    txtApp.setText(tmp.getApp());
                    txtApm.setText(tmp.getApm());
                    txtRFC.setText(tmp.getRfc());
                    switch (tmp.getTipo())
                    {
                        case 'N': cmbTipo.setSelectedIndex(0); break;
                        case 'P': cmbTipo.setSelectedIndex(1); break;
                        case 'V': cmbTipo.setSelectedIndex(2); break;
                    }
                    txtSalarioMensual.setText(String.valueOf(tmp.getSalarioMensual()));
                    txtDireccion.setText(tmp.getDireccion());
                    btnNuevo.setEnabled(false);
                    btnBuscar.setText("Modificar");
                    btnEliminar.setEnabled(true);
                    btnSalir.setText("Cancelar");
                }
                else
                {
                    JOptionPane.showMessageDialog(getMe(), "El Cliente numero \"" + val + "\" NO EXISTE", "Banco Intenacional de Hyrule(BIH)", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        else if (btnBuscar.getText().equals("Modificar"))
        {
            txtNumCliente.setEnabled(false);
            txtNombre.setEnabled(true);
            txtApp.setEnabled(true);
            txtApm.setEnabled(true);
            txtRFC.setEnabled(true);
            cmbTipo.setEnabled(true);
            txtSalarioMensual.setEnabled(true);
            txtDireccion.setEnabled(true);
            btnBuscar.setText("Guardar");
            btnEliminar.setEnabled(false);
            txtNombre.requestFocus();
        }
        else if (btnBuscar.getText().equals("Guardar"))
        {
            Clientes c;
            c=diccio.get(val);
            c.setNombre(txtNombre.getText());
            c.setApp(txtApp.getText());
            c.setApm(txtApm.getText());
            c.setRfc(txtRFC.getText());
            c.setTipo(((String)cmbTipo.getSelectedItem()).charAt(0));
            try{
                c.setSalarioMensual(Double.parseDouble(txtSalarioMensual.getText()));
            
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(getMe(),"Error en el formato del salario mensual del cliente","Banco Intenacional de Hyrule(BIH)",JOptionPane.ERROR_MESSAGE);
                return;
            }
            c.setDireccion(txtDireccion.getText());
            resetear();
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(getMe(), "¿Estas seguro de eliminarlo?", "Banco Internacional de Hyrule (BIH)", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            diccio.remove(val);
            resetear();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (btnSalir.getText().equals("Salir"))
        {
            padre.setNumCL(numCL);
            padre.setVisible(true);
            this.dispose();
        }
        else
        {
            resetear();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        padre.setNumCL(numCL);
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosing
private void resetear()
{
            txtNumCliente.setText("");
            txtNumCliente.setEnabled(true);
            txtNumCliente.setEditable(true);
            txtNombre.setEnabled(false);
            txtNombre.setText("");
            txtApp.setEnabled(false);
            txtApp.setText("");
            txtApm.setEnabled(false);
            txtApm.setText("");
            txtRFC.setEnabled(false);
            txtRFC.setText("");
            cmbTipo.setEnabled(false);
            cmbTipo.setSelectedIndex(0);
            txtSalarioMensual.setEnabled(false);
            txtSalarioMensual.setText("");
            txtDireccion.setEnabled(false);
            txtDireccion.setText("");
            btnNuevo.setText("Nuevo");
            btnBuscar.setEnabled(true);
            btnSalir.setText("Salir");
            btnNuevo.setEnabled(true);
            btnBuscar.setText("Buscar");
            btnEliminar.setEnabled(false);
            txtNumCliente.requestFocus();
}
    public Cliente getMe()
    {
        return this;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel lblApm;
    private javax.swing.JLabel lblApp;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumCliente;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblSalarioMensual;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApm;
    private javax.swing.JTextField txtApp;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCliente;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtSalarioMensual;
    // End of variables declaration//GEN-END:variables
}
