
package act2_2_xsd;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/*
    Alumno: Ari Santiago Piceno Rodríguez
    Registro:23300223
    Grado y Grupo: 4C1
    
    Materia: POO 2 (Programación Orientada a Objetos 2)
    Carrera: Desarrollo de Software
    Producto: Act4 Practica de Validacion XSD
    Profe: ROA
    
    Fecha: 15/mayo/2025
    
    */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private File archClientes;
    private File archCajeros;
    private File datos;
    private superXML XML;
    
    private HashMap<Integer, Clientes> diccioCL;
    private HashMap<Integer, Cajeros> diccioCJ;
    private int numCL = 0;
    private int numCJ = 0;
    public Principal() {
        initComponents();
        
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension d=tk.getScreenSize();
        setSize (656, 502);
        setLocation((d.width-getSize().width)/2,(d.height-getSize().height)/2);
        setTitle("Banco Internacional de Hyrule (BIH)");
        setVisible(true);
        
        archClientes = new File ("XML/clientes.xml");
        archCajeros = new File ("XML/cajeros.xml");
        datos = new File ("XML/datos.xml");
        if (archClientes.exists() && archCajeros.exists())
        {   
            if (!archClientes.isFile() && !archCajeros.isFile())
            {
               JOptionPane.showMessageDialog(getMe(),"Error al abrir el archivo XML","Banco Internacional de Hyrule (BIH)",JOptionPane.ERROR_MESSAGE);
               this.dispose();
            }
        }
        else
        {
            try {
               archClientes.createNewFile();
               archCajeros.createNewFile();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(getMe(),"Error al abrir el archivo XML","Banco Internacional de Hyrule (BIH)",JOptionPane.ERROR_MESSAGE);
               this.dispose();
            }
        }
        
        XML=new superXML(archClientes, archCajeros, datos);
        
        if (XML.validaXML() == false){
            JOptionPane.showMessageDialog(null, "HUBO UNA FALLA AL VALIDAR EL DOCUMENTO XML", "Banco Internacional de Hyrule (BIH)", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
       
        try {
            diccioCL = XML.leeXMLClientes();
            diccioCJ = XML.leeXMLCajeros();
        } catch (NullPointerException e) {
            this.dispose();
        }
        
        int[] ome = XML.leeDatosXML();
        numCL = ome[0];
        numCJ = ome[1];
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnCajeros = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnCola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(110, 350, 420, 90);

        btnCajeros.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCajeros.setText("Administrar Cajeros");
        btnCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajerosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCajeros);
        btnCajeros.setBounds(330, 110, 200, 90);

        btnClientes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnClientes.setText("Administrar Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(110, 110, 200, 90);

        btnCola.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCola.setText("Administracion de Turnos");
        btnCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCola);
        btnCola.setBounds(110, 230, 420, 90);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 20, 160, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaActionPerformed
       Turnos t=new Turnos(getMe(),diccioCL);
       getMe().setVisible(false);
       
    }//GEN-LAST:event_btnColaActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        Cliente c=new Cliente(getMe(),diccioCL, numCL);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajerosActionPerformed
        Cajero c=new Cajero(getMe(),diccioCJ, numCJ);
        this.setVisible(false);
    }//GEN-LAST:event_btnCajerosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        XML.escribirXMLClientes(diccioCL, numCL);
        XML.escribirXMLCajeros(diccioCJ, numCJ);
        XML.escribeDatosXML(numCL, numCJ);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        XML.escribirXMLClientes(diccioCL, numCL);
        XML.escribirXMLCajeros(diccioCJ, numCJ);
        XML.escribeDatosXML(numCL, numCJ);
    }//GEN-LAST:event_formWindowClosing
    public Principal getMe()
    {
        return this;
    }

    public int getNumCL() {
        return numCL;
    }

    public void setNumCL(int numCL) {
        this.numCL = numCL;
    }

    public int getNumCJ() {
        return numCJ;
    }

    public void setNumCJ(int numCJ) {
        this.numCJ = numCJ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCajeros;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCola;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
