
package act2_2_xsd;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.Queue;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/*
    Alumno: Ari Santiago Piceno Rodríguez
    Registro:23300223
    Grado y Grupo: 4C1
    
    Materia: POO 2 (Programación Orientada a Objetos 2)
    Carrera: Desarrollo de Software
    Producto: Act4 Practica de Validacion XSD
    Profe: ROA
    
    Fecha: 15/mayo/2025
    
    */
public class Turnos extends javax.swing.JFrame {

    private HashMap<Integer, Clientes> diccio;
    private Principal padre;
    private Queue colaNormal;
    private Queue colaPreferente;
    private Queue colaVIP;
    private JLabel lblCajeros[];
    private JTextField txtCajeros[];
    private Timer tmrCajeros[];
    private DefaultListModel modeloNormal;
    private DefaultListModel modeloPreferente;
    private DefaultListModel modeloVIP;
    private int contador;
    
    public Turnos(Principal padre, HashMap<Integer, Clientes> diccio) {
        initComponents();
        modeloNormal=new DefaultListModel();
        modeloPreferente=new DefaultListModel();
        modeloVIP=new DefaultListModel();
        colaNormal=new LinkedList();
        colaPreferente=new LinkedList();
        colaVIP=new LinkedList();
        this.padre=padre;
        this.diccio = diccio;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension d=tk.getScreenSize();
        setSize (606, 590);
        setLocation((d.width-getSize().width)/2,(d.height-getSize().height)/2);
        setTitle("Banco Internacional de Hyrule (BIH)");
        spnNumCajeros.setValue(1);
        lblCajeros=new JLabel[5];
        txtCajeros=new JTextField[5];
        tmrCajeros=new Timer[5];
        lstNormal.setModel(modeloNormal);
        lstPreferente.setModel(modeloPreferente);
        lstVIP.setModel(modeloVIP);
        for (contador=0;contador<5;contador++)
        {
            tmrCajeros[contador]=new Timer(1000,new ActionListener(){
                private final int posicion=getContador();
                @Override
                public void actionPerformed(ActionEvent e) {
                   if (getVIP().size()>0) 
                   {
                       getTxtCajeros()[posicion].setText(getVIP().get(0).toString());
                       getVIP().remove(0);
                       getColaVIP().poll();
                   }
                   else if (getPreferente().size()>0)
                   {
                       getTxtCajeros()[posicion].setText(getPreferente().get(0).toString());
                       getPreferente().remove(0);
                       getColaPreferente().poll();
                   }
                   else if (getNormal().size()>0)
                   {
                       getTxtCajeros()[posicion].setText(getNormal().get(0).toString());
                       getNormal().remove(0);
                       getColaNormal().poll();
                   }
                   else
                   {
                       getTxtCajeros()[posicion].setText("Terminado");
                       getTmrCajeros()[posicion].stop();
                       getAgregar().setEnabled(true);
                       for (int i=0;i<getTxtCajeros().length;i++)
                       {
                           getTxtCajeros()[i].setText("Disponible");
                       }
                   }
                }
                
            });   
            lblCajeros[contador]=new JLabel();
            lblCajeros[contador].setSize(50,15);
            lblCajeros[contador].setText("Cajero "+(contador+1));
            lblCajeros[contador].setLocation (150,400+(contador*30));
            txtCajeros[contador]=new JTextField();
            txtCajeros[contador].setSize(120,25);
            txtCajeros[contador].setText("Disponible");
            txtCajeros[contador].setLocation (210,395+(contador*30));
            txtCajeros[contador].setEditable(false);
            lblCajeros[contador].setVisible(false);
            txtCajeros[contador].setVisible(false);
            
            add(txtCajeros[contador]);
            add(lblCajeros[contador]);
            
        }
        lblCajeros[0].setVisible(true);
        txtCajeros[0].setVisible(true);
            
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumCliente = new javax.swing.JLabel();
        txtNumCliente = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVIP = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNormal = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPreferente = new javax.swing.JList<>();
        lblNormal = new javax.swing.JLabel();
        lblPreferente = new javax.swing.JLabel();
        lblVIP = new javax.swing.JLabel();
        lblCantidadCajeros = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        spnNumCajeros = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblNumCliente.setText("Numero de Cliente:");
        getContentPane().add(lblNumCliente);
        lblNumCliente.setBounds(50, 90, 120, 40);
        getContentPane().add(txtNumCliente);
        txtNumCliente.setBounds(180, 90, 240, 40);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(450, 90, 100, 30);

        jScrollPane1.setViewportView(lstVIP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 190, 100, 130);

        jScrollPane2.setViewportView(lstNormal);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 190, 100, 130);

        jScrollPane3.setViewportView(lstPreferente);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(230, 190, 100, 130);

        lblNormal.setText("Normal");
        getContentPane().add(lblNormal);
        lblNormal.setBounds(80, 160, 70, 16);

        lblPreferente.setText("Preferente");
        getContentPane().add(lblPreferente);
        lblPreferente.setBounds(250, 160, 80, 16);

        lblVIP.setText("VIP");
        getContentPane().add(lblVIP);
        lblVIP.setBounds(450, 160, 60, 16);

        lblCantidadCajeros.setText("Cantidad de Cajeros");
        getContentPane().add(lblCantidadCajeros);
        lblCantidadCajeros.setBounds(140, 360, 130, 16);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(410, 360, 80, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("TURNOS DE ATENCION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 430, 30);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(460, 490, 110, 50);

        spnNumCajeros.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnNumCajeros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnNumCajerosStateChanged(evt);
            }
        });
        getContentPane().add(spnNumCajeros);
        spnNumCajeros.setBounds(290, 360, 64, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtNumCliente.getText().equals(""))
        {
            Clientes tmp=null;
            try{
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(getMe(),"El Formato del Numero de Cliente NO es el Adecuado","Banco Intenacional de Hyrule(BIH)", JOptionPane.ERROR_MESSAGE);
                    return;
            }
            int val=Integer.parseInt(txtNumCliente.getText());
            if (diccio.get(val) != null)
            {
                tmp = diccio.get(val);
                switch (tmp.getTipo())
                {
                    case 'N':
                                modeloNormal.add(modeloNormal.getSize(), tmp.getNombre());
                                colaNormal.add(val);
                                break;
                    case 'P':
                                modeloPreferente.add(modeloPreferente.getSize(), tmp.getNombre());
                                colaPreferente.add(val);
                                break;
                    case 'V':
                                modeloVIP.add(modeloVIP.getSize(), tmp.getNombre());
                                colaVIP.add(val);
                                break;
                }
                
            
            }
            else
            {
                JOptionPane.showMessageDialog(getMe(), "El cliente no existe!!","Banco Internacional de Hyrule (BIH)",JOptionPane.WARNING_MESSAGE);
            }
            
                
        }
        else
        {
            JOptionPane.showMessageDialog(getMe(), "Ingresa el numero de cliente", "Banco Internacional de Hyrule", JOptionPane.ERROR_MESSAGE);
            txtNumCliente.requestFocus();
        }
        txtNumCliente.setText("");
        txtNumCliente.requestFocus();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        for (int i=0;i<(Integer)spnNumCajeros.getValue();i++)
        {
            tmrCajeros[i].start();
            
        }
        btnAgregar.setEnabled(false);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void spnNumCajerosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnNumCajerosStateChanged
        for (int i=0;i<5;i++)
        {
            if (i<=((Integer)spnNumCajeros.getValue())-1)
            {
                lblCajeros[i].setVisible(true);
                txtCajeros[i].setVisible(true);
            }
            else
            {
                lblCajeros[i].setVisible(false);
                txtCajeros[i].setVisible(false);
            }
        }
    }//GEN-LAST:event_spnNumCajerosStateChanged
    
    private Turnos getMe()
    {
        return this;
    }
    private Queue getColaPreferente()
    {
        return colaPreferente;
    }
    private Queue getColaNormal()
    {
        return colaNormal;
    }
    private Queue getColaVIP()
    {
        return colaVIP;
    }
    private DefaultListModel getPreferente()
    {
        return modeloPreferente;
    }
    private DefaultListModel getNormal()
    {
        return modeloNormal;
    }
    private DefaultListModel getVIP()
    {
        return modeloVIP;
    }
    private JTextField[] getTxtCajeros()
    {
        return txtCajeros;
    }
    private Timer[] getTmrCajeros()
    {
        return tmrCajeros;
    }
    private int getContador()
    {
        return contador;
    }
    private JButton getAgregar()
    {
        return btnAgregar;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCantidadCajeros;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblNumCliente;
    private javax.swing.JLabel lblPreferente;
    private javax.swing.JLabel lblVIP;
    private javax.swing.JList<String> lstNormal;
    private javax.swing.JList<String> lstPreferente;
    private javax.swing.JList<String> lstVIP;
    private javax.swing.JSpinner spnNumCajeros;
    private javax.swing.JTextField txtNumCliente;
    // End of variables declaration//GEN-END:variables
}
